name: Bump Version

on:
  push:
    branches: [ master ]
    paths-ignore:
      - everest.yaml

jobs:
  bump:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v4.1.0
        with:
          python-version: 3.10.5
      
      - name: Install Python Libraries
        run: |
          pip install pyyaml
        
      - name: Bump Mod Version
        run: python "./.github/scripts/update-yml.py"
      
      - name: Update Repository
        uses: test-room-7/action-update-file@v1
        with:
          file-path: everest.yaml
          commit-msg: Bump mod version
          branch: master
          github-token: ${{ secrets.ACCESS_TOKEN }}
        
          
