name: Release

on:
  release:
    types: [published]
jobs:
  release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup Python
        uses: actions/setup-python@v4.1.0
        with:
          python-version: 3.10.5

      - name: Install Python Libraries
        run: |
          pip install pyyaml

      - name: Get Dependencies
        run: |
          curl "${{ secrets.BUILDDEPS }}" -o "./download.zip"
          mkdir "deps"
          Expand-Archive -Path "./download.zip" -DestinationPath "./deps/"

      - name: Build
        run: msbuild PuzzleHelper.sln /p:Configuration=Release

      - name: Set version
        run: python "./.github/scripts/update-yml.py" -v "${{ github.event.release.tag_name }}"

      - name: Update Repository
        uses: test-room-7/action-update-file@v1
        with:
          file-path: everest.yaml
          commit-msg: Bump mod version
          branch: master
          github-token: ${{ secrets.ACCESS_TOKEN }}

      - name: Update everest.yaml
        run: python "./.github/scripts/update-yml.py" -r -v "${{ github.event.release.tag_name }}" -dll "PuzzleHelper.dll"

      - name: Package Mod
        run: |
          mkdir modfiles
          Move-Item -Path "./Loenn" -Destination "./modfiles"
          Move-Item -Path "./bin/Release/PuzzleHelper.dll" -Destination "./modfiles"
          Move-Item -Path "./everest.yaml" -Destination "./modfiles"

      - name: Upload Artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: PuzzleHelper
          path: ./modfiles
      
